orbs:
  heroku: circleci/heroku@1.2.3
  docker: circleci/docker@1.0.0
version: 2.1
workflows:
  deploy:
    jobs:
      - docker/publish:
          image: alexsuslin/docker-hy.github.io
          tag: 'latest'
  heroku_deploy:
    jobs:
      - heroku/push-docker-image