orbs:
  heroku: circleci/heroku@0.0.10
  docker: circleci/docker@1.0.0
version: 2.1
workflows:
  deploy:
    jobs:
      - docker/publish:
          image: alexsuslin/docker-hy.github.io
          tag: 'latest'
  heroku_deploy:
    jobs:
      - intall
      - push-docker-image
