version: 2.1
orbs:
  docker: circleci/docker@1.0.0
  aws-code-deploy: circleci/aws-code-deploy@0.0.11
workflows:
  deploy:
    jobs:
      - docker/publish:
          image: alexsuslin/docker-hy.github.io
          tag: 'latest'
      - aws-code-deploy/deploy:
          application-name: alexsuslin-docker-hy
          deployment-group: myDeploymentGroup
          service-role-arn: myDeploymentGroupRoleARN
          bundle-bucket: myApplicationS3Bucket
          bundle-key: myS3BucketKey
