orbs:
  deploy-to-heroku: betterdoc/deploy-to-heroku@4.2.0
  docker: circleci/docker@1.0.0
version: 2.1
workflows:
  deploy:
    jobs:
      - docker/publish:
          image: alexsuslin/docker-hy.github.io
          tag: 'latest'
  heroku_deploy:
    jobs:
      - betterdoc/docker-build-release