version: 2
jobs:
  build:
    machine: true

    working_directory: ~/myapp

    steps:
      - checkout

      - run:
          name: Build Docker image
          command: docker build -t alexsuslin/docker-hy.github.io .

      - run:
          name: Push to DockerHub
          command: |
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            docker push alexsuslin/docker-hy.github.io

      - run:
          name: Deploy to heroku
          command: |
            echo "$HEROKU_API_KEY" | docker login --username $HEROKU_LOGIN --password-stdin registry.heroku.command
            docker tag alexsuslin/docker-hy.github.io registry.heroku.com/$HEROKU_APP_NAME/web
            docker push registry.heroku.com/$HEROKU_APP_NAME/web